AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  S3BucketName:
    Description: Enter a S3 bucket name to store artifacts.
    Type: String
    #Default: "cpipline-test"
  LogBucketName:
    Description: Enter a S3 bucket name to store artifacts.
    Type: String
    #Default: "codepipeline-us-east-1-360078336"
  GithubRepo:
    Description: Enter Github repository name.
    Type: String
    #Default: "code-pipeline-cloudformation"
  GithubBranch:
    Description: Enter branch name of the repository.
    Type: String
    #Default: "main"
  GithubOwner:
    Description: Enter Github Owner's name.
    Type: String
    #Default: "dwops-git"
  GithubToken:
    Description: Enter Github Access Token.
    Type: String
    #Default: "****"
Metadata:
  Generator: "former2"
Description: "An AWS Code Pipeline"
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value:  !Join ['', [!Ref "AWS::StackName", "-VPC" ]]
 